eureka:
instance:
hostname: localhost
client:
service-url:
defaultZone: http://localhost:8888/eureka

server:
port:8070
spring:
  application:
    name: schools
  config:
    import: optinal:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto:create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    confin:
      students-url: http://localhost:8222/api/v1/students
